# Exp no-1
## Develop a python program to read n digit integer number,and seperate the integer number and display each digit.

In [11]:
n=int(input("Enter the number of digits:"))
if n>0:
   number=int(input(f"Enter a {n}-digit integer:"))
   if number>=10**(n-1) and number<10**n:
      for i in range(n):
            digit=number//(10**(n-1))
            print(digit)
            number%=10**(n-1)
            n-=1
   else:
       print(f"Please enter a {n}-digit integer;")
else:
    print("Please enter a valid number of digits(greater than 0).")

Enter the number of digits:2
Enter a 2-digit integer:1
Please enter a 2-digit integer;


# Exp no-2
## Develop a python program to accept 4 numbers and display them in sorted order using a minimum number of if else statements.

In [12]:
a=int(input("Enter the first number:"))
b=int(input("Enter the second number:"))
c=int(input("Enter the third number:"))
d=int(input("Enter the forth number:"))
if a<b:a,b=b,a
if c<d:c,d=d,c
if a<c:a,c=c,a
if b<d:b,d=d,b
if b<c:b,c=c,b
print("The sorted numbers are:",a,b,c,d)

Enter the first number:1
Enter the second number:2
Enter the third number:3
Enter the forth number:4
The sorted numbers are: 4 3 2 1


## Exp-4
### Develop a program for checking if a given n digit number is palindrome or not.

In [2]:
number=int(input("Enter an n-digit number:"))
original_number=number
reversed_number=0
                 
while number>0:
    digit=number%10
    reversed_number=reversed_number*10+digit
    number//=10
if original_number==reversed_number:
   print("Palindrome")
else:
    print("Not a Palindrome")

Enter an n-digit number:121
Palindrome


# Exp-5
## Develop a python script to display a multiplication table for given integer n


In [4]:
n=int(input("enter an integer for the multiplication table:"))
print(f"Multiplication Table for {n}:")
for i in range(1,11):
    result=n*i
    print(f"{n}x{i}={result}")

enter an integer for the multiplication table:5
Multiplication Table for 5:
5x1=5
5x2=10
5x3=15
5x4=20
5x5=25
5x6=30
5x7=35
5x8=40
5x9=45
5x10=50


## Experiment No-3

## Develop python scripts to Calculate the Mean,Median,mode,Variance and standard deviation of n integer numbers


In [7]:
n=int(input("Enter the number of elements:"))
numbers=[int(input(f"Enter number {i+1}:"))for i in range(n)]

mean=sum(numbers)/n

numbers.sort()
if n%2==0:
    median=(numbers[n//2-1]+numbers[n//2])/2
else:
    median=numbers[n//2]
frequency={num:numbers.count(num)for num in numbers}
max_count=max(frequency.values())
mode=[k for k,v in frequency.items() if v==max_count]

if len(mode)==n:
    mode="No mode"
    
mean_difference_squared_sum=sum((x-mean)**2 for x in numbers)
variance_sample=mean_difference_squared_sum/(n-1) if n>1 else 0

variance_population=mean_difference_squared_sum/n

std_deviation_sample=variance_sample**0.5
std_deviation_population=variance_population**0.5

print(f"mean:{mean}")
print(f"median:{median}")
print(f"mode:{mode}")
print(f"Sample variance:{variance_sample}")
print(f"Population variance:{variance_population}")
print(f"Sample standard deviation:{std_deviation_sample}")
print(f"Population standard deviation:{std_deviation_population}")


Enter the number of elements:4
Enter number 1:3.4
Enter number 2:4.5
Enter number 3:5.5
Enter number 4:5.6
mean:4.75
median:5.0
mode:No mode
Sample variance:1.0566666666666664
Population variance:0.7924999999999999
Sample standard deviation:1.0279429296739515
Population standard deviation:0.8902246907382427


## Exp6
### Develop a python script to rotate right about a given position in that list and display them.

In [1]:
number=int(input("Enter the integer number:"))

revs_number=0
while(number>0):
    remainder=number%10
    revs_number=(revs_number*10)+remainder
    number=number//10
print("the reverse number is:{}".format(revs_number))

Enter the integer number:234
the reverse number is:432


# Exp7
## Develop Write a python script to interchange the digits of a given integer number

In [3]:
def interchange_digits(number,pos1,pos2):
    
    number_str=str(number)
    number_list=list(number_str)
    number_list[pos1-1],number_list[pos2-1]=number_list[pos2-1],number_list[pos1-1]
    interchanged_number=int(''.join(number_list))
    return interchanged_number
number=int(input("Enter the user input:"))
pos1=int(input("enter the 1st position which u want to swap:"))
pos2=int(input("enter the 2nd position which u want to swap:"))

interchanged_number=interchange_digits(number,pos1,pos2)
print("Original number:",number)
print("Interchanged number:",interchanged_number)

Enter the user input:56789
enter the 1st position which u want to swap:1
enter the 2nd position which u want to swap:4
Original number: 56789
Interchanged number: 86759


# EXP-8
## Develop a python program to capitalize a given list of strings.

In [3]:
def capitalize_strings(string_list):
    return[s.capitalize() for s in string_list]
input_strings=['hello','good','how','simple']
capitalize_strings=capitalize_strings(input_strings)
print(capitalize_strings)

['Hello', 'Good', 'How', 'Simple']


# EXP-9
## Using a dictionary develop a python ,program to determine and print the number of duplicate words in a sentence

In [7]:
def count_duplicate_words(sentence):
    words=sentence.split()
    word_count={}
    for word in words:
        word=word.lower()
        if word in word_count:
            word_count[word]+=1
        else:
            word_count[word]=1
    duplicates={word:count for word,count in word_count.items() if count>1}
    
    if duplicates:
        print("Duplicate words and their counts:")
        for word,count in duplicates.items():
            print(f"{word}:{count}")
    else:
        print("No duplicate words found.")
sentence=input("Enter a sentence:")
count_duplicate_words(sentence)

Enter a sentence:big black bug bit a big black dog on his big black nose
Duplicate words and their counts:
big:3
black:3


# EXP-10:Develop python program to read Numpy array and print row(sum,mean,std) and column(sum,mean,std)

In [2]:
from numpy import asarray

data=[[1,2,3],[4,5,6]]

data=asarray(data)

print("Numpy Array")
print(data)
print("__________________________")

totalr=data.sum(axis=1)
totalc=data.sum(axis=0)

print("Row Sum")
print(totalr)
print("Column Sum")
print(totalc)
print("__________________________")
meanr=data.mean(axis=1)
meanc=data.mean(axis=0)
print("Row Mean")
print(meanr)
print("Column Mean")
print(meanc)
print("__________________________")
stdr=data.std(axis=1)
stdc=data.std(axis=0)
print("Row STD")
print(stdr)
print("Column STD")
print(stdc)

Numpy Array
[[1 2 3]
 [4 5 6]]
__________________________
Row Sum
[ 6 15]
Column Sum
[5 7 9]
__________________________
Row Mean
[2. 5.]
Column Mean
[2.5 3.5 4.5]
__________________________
Row STD
[0.81649658 0.81649658]
Column STD
[1.5 1.5 1.5]


# EXP 11:Develop a python program to read and print in the console CSV file.

In [4]:
import csv

file=open('employee_birthday.csv',mode='r')
csv_reader=csv.reader(file,delimiter=',')
line_count=0

for row in csv_reader:
    if line_count==0:
        print(f'Column names are {",".join(row)}')
        line_count +=1
    else:
        print(f'\t{row[0]} works in the {row[1]} department,and was born in {row[2]}.')
        line_count +=1
        
print(f'processed {line_count} lines')

Column names are name,department,birthday_month
	John Smith works in the Accounting department,and was born in november.
	Erica Meyers works in the IT department,and was born in March.
	Rocky works in the HR department,and was born in April.
processed 4 lines
